title: Portfolio
remote_theme: pages-themes/minimal@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
logo: /docs/assets/images/Portrait_circle.png
author:
  name: Sebastian Ghafafian
  email: sghafafian@gmail.com
  linkedin: https://www.linkedin.com/
description: |
  Data scientist and mechanical engineer with four years of experience at the
  intersection of industry and academia. Creative problem solver with an eye for
  detail. Collaborative and fast learner able to tackle new challenges with a
  positive attitude. 
  - <a href="https://www.linkedin.com/in/sebastian-ghafafian">👔 LinkedIn</a> 
  - <a href="https://www.linkedin.com/in/sebastian-ghafafian">👔 LinkedIn</a> 
  - Feel free to contact me 
  - sghafafian@gmail.com
github_link: https://github.com/yaoyao-liu/minimal-light
linkedin: https://www.linkedin.com/

